# General Jekyll Config
highlighter: pygments
url: http://ludwiktrammer.github.io
lsi: true
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]
permalink: /:categories/:title.html
